### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by marilirulita**
- build with ruby
- make my own version of popular enumerable methods in ruby

### CODE REVIEW

**Review by MarilenaRoque — CHANGES_REQUESTED** [review]
# Hey @marilirulita ! :robot:

### Good Job on your project, so far!
Now, let's adjust the behavior of your function in order to achieve the same return expected for the original methods of ruby.  💪🏻😃

## Changes Required ♻️ 

- [x] #my_map, #my_each and #my_each_with index should return an enumerator when no block is provided.
- [x] #My_each and #My_each_with_index should be able to be called on a range or a hash and should present the same behavior of the original methods of ruby.
- [x]  #my_inject should be able to receive a symbol as argument with or without a initial value. [1,1,1].my_inject(:*) or [1,1,1].my_inject(2, :*)
- [x] #My_map presents the same behavior of ruby's map when receiving a proc.
- [x] #my_none, #my_all, and #my_any should work identical and return the same thing as ruby's original methods.

**To fix your methods behavior:**  Please check the documentation for the original Enumerable methods [here](https://ruby-doc.org/core-3.0.0/Enumerable.html). You will see that after the explanation there is a box with examples with different inputs for the method. Make sure that your method also covers all these types of input.

Feel free to message me on Slack, if you need further info about the review.
Happy Coding!!! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

**Review by Georjane — CHANGES_REQUESTED** [review]
## Status: Changes Required 🛑 🔧 
### Hi there Team ✋🏽 
Very impressive work you have done so far with the enumerable methods. Almost all test cases are passing. Just the following few test cases are left:

- [x] enumerables #my_each when a block is given when self is a hash behaves like #each calls the given block once for each element in self.
- [x] enumerables #my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
- [x] enumerables #my_select returns an enumerator if no block is given
- [x] enumerables #my_inject raises a "LocalJumpError" when no block or argument is given
Please kindly fix these issues and request another code review.

_Feel free to reach out to me on Slack if you have any questions, Witah Georjane_ 🤝 
Good luck on your project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

**Review by SmithVyne — CHANGES_REQUESTED** [review]
Changes Required 👋 👋 
Hello @marilirulita, you have a really impressive project here. I love the quality and compactness of your code. Anyway, you need to make some improvements to it so your `my_each` and `my_each_with_index` methods work like the `each` and `each_with_index` methods. 

[REQUIRED] - Your `my_each `and `my_each_with_index` methods both do not work with hashes right now. 
You need to update them to support hashes. For example, `my_each` should be able to go over a hash and run the block on each `key, value pair`. Do the same for the `my_each_with_index` method also.

Fix this and submit your project for re-review. You should get approval, hopefully.

**Review by cristianCeamatu — APPROVED** [review]
### 🥇 APPROVED 🥇 Congratulations and good luck with the next projects!

If you ever need any help or notice that you are wasting too many hours on a bug don't hesitate to contact me on Slack.

Best regards,
Cristian Ceamatu
Slack: Cristian Viorel Ceamatu

**Pull request merged**
